os:
- osx
- linux

addons:
  apt:
    packages:
    - build-essential
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev

language: node_js
node_js:
- '10'
- '12'

cache:
  directories:
  - node_modules

script:
- npm run test
